"""
World's Front Page — Master Source List
163 publications across 60+ countries.
Each source: (id, country, region, name, url, status, icij)
Status: "independent" | "state_controlled" | "state_affiliated" | "state_adjacent" | "exile" | "pressured"
"""

SOURCES = [
    # ──── AMERICAS ────
    {"id": 'nyt', "country": 'USA', "region": 'Americas', "name": 'The New York Times', "url": 'https://www.nytimes.com', "status": 'independent', "icij": True, "frontpage": {"provider": "kiosko", "country_code": "us", "slug": "newyork_times", "fallback": {"provider": "frontpages", "slug": "the-new-york-times", "country_slug": "us"}}},
    {"id": 'wsj', "country": 'USA', "region": 'Americas', "name": 'The Wall Street Journal', "url": 'https://www.wsj.com', "status": 'independent', "icij": False, "frontpage": {"provider": "kiosko", "country_code": "us", "slug": "wsj"}},
    {"id": 'wapo', "country": 'USA', "region": 'Americas', "name": 'The Washington Post', "url": 'https://www.washingtonpost.com', "status": 'independent', "icij": True, "frontpage": {"provider": "kiosko", "country_code": "us", "slug": "washington_post", "fallback": {"provider": "frontpages", "slug": "the-washington-post", "country_slug": "us"}}},
    {"id": 'globe_mail', "country": 'Canada', "region": 'Americas', "name": 'The Globe and Mail', "url": 'https://www.theglobeandmail.com', "status": 'independent', "icij": True, "frontpage": {"provider": "kiosko", "country_code": "ca", "slug": "ca_globe_mail", "fallback": {"provider": "frontpages", "slug": "the-globe-and-mail", "country_slug": "canada"}}},
    {"id": 'nat_post', "country": 'Canada', "region": 'Americas', "name": 'National Post', "url": 'https://nationalpost.com', "status": 'independent', "icij": False, "frontpage": {"provider": "kiosko", "country_code": "ca", "slug": "ca_national_post", "fallback": {"provider": "frontpages", "slug": "national-post", "country_slug": "canada"}}},
    {"id": 'el_universal', "country": 'Mexico', "region": 'Americas', "name": 'El Universal', "url": 'https://www.eluniversal.com.mx', "status": 'independent', "icij": False, "frontpage": {"provider": "kiosko", "country_code": "mx", "slug": "mx_universal", "fallback": {"provider": "frontpages", "slug": "el-universal-mexico", "country_slug": "mexico"}}},
    {"id": 'reforma', "country": 'Mexico', "region": 'Americas', "name": 'Reforma', "url": 'https://www.reforma.com', "status": 'independent', "icij": False, "frontpage": {"provider": "kiosko", "country_code": "mx", "slug": "mx_reforma", "fallback": {"provider": "frontpages", "slug": "reforma", "country_slug": "mexico"}}},
    {"id": 'folha', "country": 'Brazil', "region": 'Americas', "name": 'Folha de S.Paulo', "url": 'https://www.folha.uol.com.br', "status": 'independent', "icij": True, "frontpage": {"provider": "kiosko", "country_code": "br", "slug": "br_folha_spaulo", "fallback": {"provider": "frontpages", "slug": "folha-de-s-paulo", "country_slug": "brazil"}}},
    {"id": 'oglobo', "country": 'Brazil', "region": 'Americas', "name": 'O Globo', "url": 'https://oglobo.globo.com', "status": 'independent', "icij": False, "frontpage": {"provider": "frontpages", "slug": "o-globo", "country_slug": "brazil"}},
    {"id": 'la_nacion', "country": 'Argentina', "region": 'Americas', "name": 'La Nación', "url": 'https://www.lanacion.com.ar', "status": 'independent', "icij": True, "frontpage": {"provider": "kiosko", "country_code": "ar", "slug": "nacion", "fallback": {"provider": "frontpages", "slug": "la-nacion", "country_slug": "argentina"}}},
    {"id": 'el_tiempo', "country": 'Colombia', "region": 'Americas', "name": 'El Tiempo', "url": 'https://www.eltiempo.com', "status": 'independent', "icij": False},
    {"id": 'el_mercurio', "country": 'Chile', "region": 'Americas', "name": 'El Mercurio', "url": 'https://www.emol.com', "status": 'independent', "icij": False, "frontpage": {"provider": "kiosko", "country_code": "cl", "slug": "cl_mercurio"}},
    {"id": 'el_nacional', "country": 'Venezuela', "region": 'Americas', "name": 'El Nacional', "url": 'https://www.elnacional.com', "status": 'exile', "icij": False},
    {"id": 'granma', "country": 'Cuba', "region": 'Americas', "name": 'Granma', "url": 'http://www.granma.cu', "status": 'state_controlled', "icij": False, "frontpage": {"provider": "kiosko", "country_code": "cu", "slug": "cu_granma"}},
    {"id": 'gleaner', "country": 'Jamaica', "region": 'Americas', "name": 'Jamaica Gleaner', "url": 'https://jamaica-gleaner.com', "status": 'independent', "icij": False},
    {"id": 'el_comercio', "country": 'Peru', "region": 'Americas', "name": 'El Comercio', "url": 'https://elcomercio.pe', "status": 'independent', "icij": False, "frontpage": {"provider": "kiosko", "country_code": "pe", "slug": "pe_comercio"}},
    {"id": 'prensa_libre_gt', "country": 'Guatemala', "region": 'Americas', "name": 'Prensa Libre', "url": 'https://www.prensalibre.com', "status": 'independent', "icij": False},
    {"id": 'la_nacion_cr', "country": 'Costa Rica', "region": 'Americas', "name": 'La Nación (Costa Rica)', "url": 'https://www.nacion.com', "status": 'independent', "icij": False},
    {"id": 'la_prensa_pa', "country": 'Panama', "region": 'Americas', "name": 'La Prensa (Panama)', "url": 'https://www.prensa.com', "status": 'independent', "icij": False},
    {"id": 'la_prensa_ni', "country": 'Nicaragua', "region": 'Americas', "name": 'La Prensa (Nicaragua)', "url": 'https://www.laprensani.com', "status": 'exile', "icij": False},
    {"id": 'el_universo', "country": 'Ecuador', "region": 'Americas', "name": 'El Universo', "url": 'https://www.eluniverso.com', "status": 'independent', "icij": False},
    {"id": 'el_deber', "country": 'Bolivia', "region": 'Americas', "name": 'El Deber', "url": 'https://eldeber.com.bo', "status": 'independent', "icij": False},
    {"id": 'abc_color', "country": 'Paraguay', "region": 'Americas', "name": 'ABC Color', "url": 'https://www.abc.com.py', "status": 'independent', "icij": False},
    {"id": 'el_pais_uy', "country": 'Uruguay', "region": 'Americas', "name": 'El País (Uruguay)', "url": 'https://www.elpais.com.uy', "status": 'independent', "icij": False},
    {"id": 'listin_diario', "country": 'Dominican Republic', "region": 'Americas', "name": 'Listín Diario', "url": 'https://listindiario.com', "status": 'independent', "icij": False},
    {"id": 'trinidad_express', "country": 'Trinidad and Tobago', "region": 'Americas', "name": 'Trinidad Express', "url": 'https://trinidadexpress.com', "status": 'independent', "icij": False},
    {"id": 'la_prensa_hn', "country": 'Honduras', "region": 'Americas', "name": 'La Prensa (Honduras)', "url": 'https://www.laprensa.hn', "status": 'independent', "icij": False},
    {"id": 'la_prensa_grafica_sv', "country": 'El Salvador', "region": 'Americas', "name": 'La Prensa Gráfica', "url": 'https://www.laprensagrafica.com', "status": 'pressured', "icij": False},
    {"id": 'amandala_bz', "country": 'Belize', "region": 'Americas', "name": 'Amandala', "url": 'https://amandala.com.bz', "status": 'independent', "icij": False},
    {"id": 'le_nouvelliste_ht', "country": 'Haiti', "region": 'Americas', "name": 'Le Nouvelliste', "url": 'https://lenouvelliste.com', "status": 'independent', "icij": False},
    {"id": 'nation_news_bb', "country": 'Barbados', "region": 'Americas', "name": 'Nation News', "url": 'https://www.nationnews.com', "status": 'independent', "icij": False},
    {"id": 'tribune_bs', "country": 'Bahamas', "region": 'Americas', "name": 'The Tribune (Bahamas)', "url": 'https://www.tribune242.com', "status": 'independent', "icij": False},

    # ──── EUROPE (incl. Caucasus & Central Asia) ────
    {"id": 'ft', "country": 'UK', "region": 'Europe', "name": 'Financial Times', "url": 'https://www.ft.com', "status": 'independent', "icij": False, "frontpage": {"provider": "frontpages", "slug": "financial-times", "country_slug": "uk"}},
    {"id": 'guardian', "country": 'UK', "region": 'Europe', "name": 'The Guardian', "url": 'https://www.theguardian.com', "status": 'independent', "icij": True},
    {"id": 'the_times', "country": 'UK', "region": 'Europe', "name": 'The Times', "url": 'https://www.thetimes.co.uk', "status": 'independent', "icij": False},
    {"id": 'irish_times', "country": 'Ireland', "region": 'Europe', "name": 'Irish Times', "url": 'https://www.irishtimes.com', "status": 'independent', "icij": True, "frontpage": {"provider": "kiosko", "country_code": "ie", "slug": "irish_times", "fallback": {"provider": "frontpages", "slug": "the-irish-times", "country_slug": "ireland"}}},
    {"id": 'le_monde', "country": 'France', "region": 'Europe', "name": 'Le Monde', "url": 'https://www.lemonde.fr', "status": 'independent', "icij": True, "frontpage": {"provider": "frontpages", "slug": "le-monde", "country_slug": "france"}},
    {"id": 'le_figaro', "country": 'France', "region": 'Europe', "name": 'Le Figaro', "url": 'https://www.lefigaro.fr', "status": 'independent', "icij": False, "frontpage": {"provider": "frontpages", "slug": "le-figaro", "country_slug": "france"}},
    {"id": 'faz', "country": 'Germany', "region": 'Europe', "name": 'Frankfurter Allgemeine', "url": 'https://www.faz.net', "status": 'independent', "icij": False, "frontpage": {"provider": "frontpages", "slug": "frankfurter-allgemeine-zeitung", "country_slug": "germany"}},
    {"id": 'sz', "country": 'Germany', "region": 'Europe', "name": 'Süddeutsche Zeitung', "url": 'https://www.sueddeutsche.de', "status": 'independent', "icij": True, "frontpage": {"provider": "frontpages", "slug": "suddeutsche-zeitung", "country_slug": "germany"}},
    {"id": 'spiegel', "country": 'Germany', "region": 'Europe', "name": 'Der Spiegel', "url": 'https://www.spiegel.de', "status": 'independent', "icij": True, "frontpage": {"provider": "kiosko", "country_code": "de", "slug": "spiegel", "fallback": {"provider": "frontpages", "slug": "der-spiegel", "country_slug": "germany"}}},
    {"id": 'nzz', "country": 'Switzerland', "region": 'Europe', "name": 'Neue Zürcher Zeitung', "url": 'https://www.nzz.ch', "status": 'independent', "icij": False, "frontpage": {"provider": "kiosko", "country_code": "ch", "slug": "neue_zurcher_zeitung", "fallback": {"provider": "frontpages", "slug": "neue-zurcher-zeitung", "country_slug": "switzerland"}}},
    {"id": 'nrc', "country": 'Netherlands', "region": 'Europe', "name": 'NRC', "url": 'https://www.nrc.nl', "status": 'independent', "icij": True, "frontpage": {"provider": "kiosko", "country_code": "nl", "slug": "nrc"}},
    {"id": 'volkskrant', "country": 'Netherlands', "region": 'Europe', "name": 'de Volkskrant', "url": 'https://www.volkskrant.nl', "status": 'independent', "icij": False, "frontpage": {"provider": "kiosko", "country_code": "nl", "slug": "volkskrant", "fallback": {"provider": "frontpages", "slug": "de-volkskrant", "country_slug": "netherlands"}}},
    {"id": 'standaard', "country": 'Belgium', "region": 'Europe', "name": 'De Standaard', "url": 'https://www.standaard.be', "status": 'independent', "icij": False},
    {"id": 'der_standard', "country": 'Austria', "region": 'Europe', "name": 'Der Standard', "url": 'https://www.derstandard.at', "status": 'independent', "icij": False, "frontpage": {"provider": "frontpages", "slug": "der-standard", "country_slug": "austria"}},
    {"id": 'el_pais', "country": 'Spain', "region": 'Europe', "name": 'El País', "url": 'https://elpais.com', "status": 'independent', "icij": True, "frontpage": {"provider": "kiosko", "country_code": "es", "slug": "elpais", "fallback": {"provider": "frontpages", "slug": "el-pais", "country_slug": "spain"}}},
    {"id": 'el_mundo', "country": 'Spain', "region": 'Europe', "name": 'El Mundo', "url": 'https://www.elmundo.es', "status": 'independent', "icij": False, "frontpage": {"provider": "kiosko", "country_code": "es", "slug": "elmundo", "fallback": {"provider": "frontpages", "slug": "el-mundo", "country_slug": "spain"}}},
    {"id": 'corriere', "country": 'Italy', "region": 'Europe', "name": 'Corriere della Sera', "url": 'https://www.corriere.it', "status": 'independent', "icij": True, "frontpage": {"provider": "kiosko", "country_code": "it", "slug": "corriere_della_sera"}},
    {"id": 'repubblica', "country": 'Italy', "region": 'Europe', "name": 'La Repubblica', "url": 'https://www.repubblica.it', "status": 'independent', "icij": True},
    {"id": 'publico', "country": 'Portugal', "region": 'Europe', "name": 'Público', "url": 'https://www.publico.pt', "status": 'independent', "icij": False, "frontpage": {"provider": "kiosko", "country_code": "pt", "slug": "publico", "fallback": {"provider": "frontpages", "slug": "publico", "country_slug": "portugal"}}},
    {"id": 'dn_sweden', "country": 'Sweden', "region": 'Europe', "name": 'Dagens Nyheter', "url": 'https://www.dn.se', "status": 'independent', "icij": True, "frontpage": {"provider": "frontpages", "slug": "dagens-nyheter", "country_slug": "sweden"}},
    {"id": 'aftenposten', "country": 'Norway', "region": 'Europe', "name": 'Aftenposten', "url": 'https://www.aftenposten.no', "status": 'independent', "icij": True, "frontpage": {"provider": "frontpages", "slug": "aftenposten", "country_slug": "norway"}},
    {"id": 'politiken', "country": 'Denmark', "region": 'Europe', "name": 'Politiken', "url": 'https://politiken.dk', "status": 'independent', "icij": True},
    {"id": 'hs', "country": 'Finland', "region": 'Europe', "name": 'Helsingin Sanomat', "url": 'https://www.hs.fi', "status": 'independent', "icij": False},
    {"id": 'gazeta', "country": 'Poland', "region": 'Europe', "name": 'Gazeta Wyborcza', "url": 'https://wyborcza.pl', "status": 'independent', "icij": True, "frontpage": {"provider": "frontpages", "slug": "gazeta-wyborcza", "country_slug": "poland"}},
    {"id": 'hn_czech', "country": 'Czech Republic', "region": 'Europe', "name": 'Hospodářské noviny', "url": 'https://ihned.cz', "status": 'independent', "icij": False},
    {"id": 'telex', "country": 'Hungary', "region": 'Europe', "name": 'Telex', "url": 'https://telex.hu', "status": 'independent', "icij": False},
    {"id": 'kathimerini', "country": 'Greece', "region": 'Europe', "name": 'Kathimerini', "url": 'https://www.kathimerini.gr', "status": 'independent', "icij": False, "frontpage": {"provider": "frontpages", "slug": "kathimerini", "country_slug": "greece"}},
    {"id": 'cumhuriyet', "country": 'Turkey', "region": 'Europe', "name": 'Cumhuriyet', "url": 'https://www.cumhuriyet.com.tr', "status": 'pressured', "icij": False},
    {"id": 'hurriyet', "country": 'Turkey', "region": 'Europe', "name": 'Hürriyet', "url": 'https://www.hurriyet.com.tr', "status": 'state_adjacent', "icij": False, "frontpage": {"provider": "kiosko", "country_code": "tr", "slug": "hurriyet", "fallback": {"provider": "frontpages", "slug": "hurriyet", "country_slug": "turkey"}}},
    {"id": 'kyiv_ind', "country": 'Ukraine', "region": 'Europe', "name": 'Kyiv Independent', "url": 'https://kyivindependent.com', "status": 'independent', "icij": False},
    {"id": 'meduza', "country": 'Russia', "region": 'Europe', "name": 'Meduza', "url": 'https://meduza.io', "status": 'exile', "icij": False},
    {"id": 'tass', "country": 'Russia', "region": 'Europe', "name": 'TASS', "url": 'https://tass.com', "status": 'state_controlled', "icij": False},
    {"id": 'danas_rs', "country": 'Serbia', "region": 'Europe', "name": 'Danas', "url": 'https://www.danas.rs', "status": 'pressured', "icij": False},
    {"id": 'jutarnji', "country": 'Croatia', "region": 'Europe', "name": 'Jutarnji List', "url": 'https://www.jutarnji.hr', "status": 'independent', "icij": False},
    {"id": 'adevarul', "country": 'Romania', "region": 'Europe', "name": 'Adevărul', "url": 'https://adevarul.ro', "status": 'independent', "icij": False, "frontpage": {"provider": "frontpages", "slug": "adevarul", "country_slug": "romania"}},
    {"id": 'dnevnik_bg', "country": 'Bulgaria', "region": 'Europe', "name": 'Dnevnik', "url": 'https://www.dnevnik.bg', "status": 'independent', "icij": False},
    {"id": 'postimees', "country": 'Estonia', "region": 'Europe', "name": 'Postimees', "url": 'https://www.postimees.ee', "status": 'independent', "icij": False},
    {"id": 'lsm_lv', "country": 'Latvia', "region": 'Europe', "name": 'LSM (Latvian Public Broadcasting)', "url": 'https://eng.lsm.lv', "status": 'independent', "icij": False},
    {"id": 'delfi_lt', "country": 'Lithuania', "region": 'Europe', "name": 'Delfi', "url": 'https://www.delfi.lt', "status": 'independent', "icij": False},
    {"id": 'tengrinews', "country": 'Kazakhstan', "region": 'Europe', "name": 'Tengrinews', "url": 'https://tengrinews.kz', "status": 'state_adjacent', "icij": False},
    {"id": 'kun_uz', "country": 'Uzbekistan', "region": 'Europe', "name": 'Kun.uz', "url": 'https://kun.uz', "status": 'pressured', "icij": False},
    {"id": '24kg', "country": 'Kyrgyzstan', "region": 'Europe', "name": '24.kg', "url": 'https://24.kg', "status": 'pressured', "icij": False},
    {"id": 'delo_si', "country": 'Slovenia', "region": 'Europe', "name": 'Delo', "url": 'https://www.delo.si', "status": 'independent', "icij": False},
    {"id": 'oslobodjenje_ba', "country": 'Bosnia and Herzegovina', "region": 'Europe', "name": 'Oslobođenje', "url": 'https://www.oslobodjenje.ba', "status": 'independent', "icij": False},
    {"id": 'nova_makedonija', "country": 'North Macedonia', "region": 'Europe', "name": 'Nova Makedonija', "url": 'https://www.novamakedonija.com.mk', "status": 'independent', "icij": False},
    {"id": 'wort_lu', "country": 'Luxembourg', "region": 'Europe', "name": 'Luxemburger Wort', "url": 'https://www.wort.lu', "status": 'independent', "icij": False},
    {"id": 'times_malta', "country": 'Malta', "region": 'Europe', "name": 'Times of Malta', "url": 'https://timesofmalta.com', "status": 'independent', "icij": False, "frontpage": {"provider": "frontpages", "slug": "times-of-malta", "country_slug": "malta"}},
    {"id": 'mbl_is', "country": 'Iceland', "region": 'Europe', "name": 'Morgunblaðið', "url": 'https://www.mbl.is', "status": 'independent', "icij": False},
    {"id": 'civil_ge', "country": 'Georgia', "region": 'Europe', "name": 'Civil.ge', "url": 'https://civil.ge', "status": 'independent', "icij": False},
    {"id": 'civilnet_am', "country": 'Armenia', "region": 'Europe', "name": 'CivilNet', "url": 'https://www.civilnet.am', "status": 'independent', "icij": False},
    {"id": 'meydan_tv', "country": 'Azerbaijan', "region": 'Europe', "name": 'Meydan TV', "url": 'https://www.meydan.tv', "status": 'exile', "icij": False},
    {"id": 'trend_az', "country": 'Azerbaijan', "region": 'Europe', "name": 'Trend News', "url": 'https://trend.az', "status": 'state_controlled', "icij": False},
    {"id": 'asiaplus_tj', "country": 'Tajikistan', "region": 'Europe', "name": 'Asia-Plus', "url": 'https://asiaplustj.info', "status": 'pressured', "icij": False},
    {"id": 'chron_tm', "country": 'Turkmenistan', "region": 'Europe', "name": 'Chronicles of Turkmenistan', "url": 'https://en.hronikatm.com', "status": 'exile', "icij": False},

    # ──── AFRICA & MIDDLE EAST ────
    {"id": 'daily_mav', "country": 'South Africa', "region": 'Africa & Middle East', "name": 'Daily Maverick', "url": 'https://www.dailymaverick.co.za', "status": 'independent', "icij": True},
    {"id": 'mg_sa', "country": 'South Africa', "region": 'Africa & Middle East', "name": 'Mail & Guardian', "url": 'https://mg.co.za', "status": 'independent', "icij": False, "frontpage": {"provider": "frontpages", "slug": "mail-and-guardian", "country_slug": "south-africa"}},
    {"id": 'punch_ng', "country": 'Nigeria', "region": 'Africa & Middle East', "name": 'The Punch', "url": 'https://punchng.com', "status": 'independent', "icij": False, "frontpage": {"provider": "frontpages", "slug": "the-punch", "country_slug": "nigeria"}},
    {"id": 'daily_nation', "country": 'Kenya', "region": 'Africa & Middle East', "name": 'Daily Nation', "url": 'https://nation.africa', "status": 'independent', "icij": False, "frontpage": {"provider": "frontpages", "slug": "daily-nation-kenya", "country_slug": "kenya"}},
    {"id": 'graphic_gh', "country": 'Ghana', "region": 'Africa & Middle East', "name": 'Graphic Online', "url": 'https://www.graphic.com.gh', "status": 'state_affiliated', "icij": False},
    {"id": 'eth_herald', "country": 'Ethiopia', "region": 'Africa & Middle East', "name": 'The Ethiopian Herald', "url": 'https://press.et/herald/', "status": 'state_controlled', "icij": False},
    {"id": 'ahram', "country": 'Egypt', "region": 'Africa & Middle East', "name": 'Al-Ahram', "url": 'https://www.ahram.org.eg', "status": 'state_affiliated', "icij": False},
    {"id": 'le_matin', "country": 'Morocco', "region": 'Africa & Middle East', "name": 'Le Matin', "url": 'https://lematin.ma', "status": 'state_affiliated', "icij": False},
    {"id": 'haaretz', "country": 'Israel', "region": 'Africa & Middle East', "name": 'Haaretz', "url": 'https://www.haaretz.com', "status": 'independent', "icij": True, "frontpage": {"provider": "frontpages", "slug": "haaretz", "country_slug": "israel"}},
    {"id": 'lorient', "country": 'Lebanon', "region": 'Africa & Middle East', "name": "L'Orient-Le Jour", "url": 'https://www.lorientlejour.com', "status": 'independent', "icij": False},
    {"id": 'the_national', "country": 'UAE', "region": 'Africa & Middle East', "name": 'The National', "url": 'https://www.thenationalnews.com', "status": 'state_adjacent', "icij": False},
    {"id": 'arab_news', "country": 'Saudi Arabia', "region": 'Africa & Middle East', "name": 'Arab News', "url": 'https://www.arabnews.com', "status": 'state_affiliated', "icij": False, "frontpage": {"provider": "frontpages", "slug": "arab-news", "country_slug": "saudi-arabia"}},
    {"id": 'iran_intl', "country": 'Iran', "region": 'Africa & Middle East', "name": 'Iran International', "url": 'https://www.iranintl.com/en', "status": 'exile', "icij": False},
    {"id": 'al_rai_jo', "country": 'Jordan', "region": 'Africa & Middle East', "name": 'Al-Rai', "url": 'https://alrai.com', "status": 'state_adjacent', "icij": False},
    {"id": 'irna', "country": 'Iran', "region": 'Africa & Middle East', "name": 'IRNA', "url": 'https://en.irna.ir', "status": 'state_controlled', "icij": False},
    {"id": 'le_soleil_sn', "country": 'Senegal', "region": 'Africa & Middle East', "name": 'Le Soleil', "url": 'https://lesoleil.sn', "status": 'state_affiliated', "icij": False},
    {"id": 'frat_mat', "country": 'Ivory Coast', "region": 'Africa & Middle East', "name": 'Fraternité Matin', "url": 'https://www.fratmat.info', "status": 'state_affiliated', "icij": False},
    {"id": 'cam_tribune', "country": 'Cameroon', "region": 'Africa & Middle East', "name": 'Cameroon Tribune', "url": 'https://www.cameroon-tribune.cm', "status": 'state_controlled', "icij": False},
    {"id": 'actualite_cd', "country": 'DR Congo', "region": 'Africa & Middle East', "name": 'Actualite.cd', "url": 'https://actualite.cd', "status": 'independent', "icij": False},
    {"id": 'el_watan', "country": 'Algeria', "region": 'Africa & Middle East', "name": 'El Watan', "url": 'https://www.elwatan.com', "status": 'pressured', "icij": False},
    {"id": 'la_presse_tn', "country": 'Tunisia', "region": 'Africa & Middle East', "name": 'La Presse (Tunisia)', "url": 'https://www.lapresse.tn', "status": 'state_affiliated', "icij": False},
    {"id": 'libya_obs', "country": 'Libya', "region": 'Africa & Middle East', "name": 'Libya Observer', "url": 'https://www.libyaobserver.ly', "status": 'independent', "icij": False},
    {"id": 'gulf_times', "country": 'Qatar', "region": 'Africa & Middle East', "name": 'Gulf Times', "url": 'https://www.gulf-times.com', "status": 'state_adjacent', "icij": False, "frontpage": {"provider": "frontpages", "slug": "gulf-times", "country_slug": "qatar"}},
    {"id": 'al_mada', "country": 'Iraq', "region": 'Africa & Middle East', "name": 'Al Mada', "url": 'https://www.almadapaper.net', "status": 'pressured', "icij": False},
    {"id": 'jornal_angola', "country": 'Angola', "region": 'Africa & Middle East', "name": 'Jornal de Angola', "url": 'https://www.jornaldeangola.ao', "status": 'state_controlled', "icij": False},
    {"id": 'noticias_mz', "country": 'Mozambique', "region": 'Africa & Middle East', "name": 'Notícias', "url": 'https://www.jornalnoticias.co.mz', "status": 'state_adjacent', "icij": False},
    {"id": 'herald_zw', "country": 'Zimbabwe', "region": 'Africa & Middle East', "name": 'The Herald (Zimbabwe)', "url": 'https://www.herald.co.zw', "status": 'state_controlled', "icij": False},
    {"id": 'newsday_zw', "country": 'Zimbabwe', "region": 'Africa & Middle East', "name": 'NewsDay (Zimbabwe)', "url": 'https://www.newsday.co.zw', "status": 'independent', "icij": False},
    {"id": 'daily_monitor_ug', "country": 'Uganda', "region": 'Africa & Middle East', "name": 'Daily Monitor', "url": 'https://www.monitor.co.ug', "status": 'pressured', "icij": False},
    {"id": 'al_ghad_jo', "country": 'Jordan', "region": 'Africa & Middle East', "name": 'Al Ghad', "url": 'https://alghad.com', "status": 'independent', "icij": False},
    {"id": 'citizen_tz', "country": 'Tanzania', "region": 'Africa & Middle East', "name": 'The Citizen (Tanzania)', "url": 'https://www.thecitizen.co.tz', "status": 'independent', "icij": False},
    {"id": 'news_diggers_zm', "country": 'Zambia', "region": 'Africa & Middle East', "name": 'News Diggers!', "url": 'https://www.newsdiggers.org', "status": 'independent', "icij": False},
    {"id": 'mmegi_bw', "country": 'Botswana', "region": 'Africa & Middle East', "name": 'Mmegi', "url": 'https://www.mmegi.bw', "status": 'independent', "icij": False},
    {"id": 'namibian', "country": 'Namibia', "region": 'Africa & Middle East', "name": 'The Namibian', "url": 'https://www.namibian.com.na', "status": 'independent', "icij": False},
    {"id": 'canal_mz', "country": 'Mozambique', "region": 'Africa & Middle East', "name": 'Canal de Moçambique', "url": 'https://canal.co.mz', "status": 'pressured', "icij": False},
    {"id": 'novo_jornal_ao', "country": 'Angola', "region": 'Africa & Middle East', "name": 'Novo Jornal', "url": 'https://novojornal.co.ao', "status": 'independent', "icij": False},
    {"id": 'new_times_rw', "country": 'Rwanda', "region": 'Africa & Middle East', "name": 'The New Times', "url": 'https://www.newtimes.co.rw', "status": 'state_adjacent', "icij": False},
    {"id": 'essor_ml', "country": 'Mali', "region": 'Africa & Middle East', "name": "L'Essor", "url": 'https://essor.ml', "status": 'state_controlled', "icij": False},
    {"id": 'sidwaya_bf', "country": 'Burkina Faso', "region": 'Africa & Middle East', "name": 'Sidwaya', "url": 'https://sidwaya.info', "status": 'state_controlled', "icij": False},
    {"id": 'sahel_ne', "country": 'Niger', "region": 'Africa & Middle East', "name": 'Le Sahel', "url": 'https://www.lesahel.org', "status": 'state_controlled', "icij": False},
    {"id": 'sudan_tribune', "country": 'Sudan', "region": 'Africa & Middle East', "name": 'Sudan Tribune', "url": 'https://sudantribune.com', "status": 'exile', "icij": False},
    {"id": 'hiiraan_so', "country": 'Somalia', "region": 'Africa & Middle East', "name": 'Hiiraan Online', "url": 'https://www.hiiraan.com', "status": 'independent', "icij": False},
    {"id": 'alquds_ps', "country": 'Palestinian Territories', "region": 'Africa & Middle East', "name": 'Al-Quds', "url": 'https://www.alquds.com', "status": 'independent', "icij": False, "frontpage": {"provider": "frontpages", "slug": "al-quds", "country_slug": "palestine"}},
    {"id": 'leprogres_td', "country": 'Chad', "region": 'Africa & Middle East', "name": 'Le Progrès (Chad)', "url": 'https://leprogrestd.com', "status": 'state_affiliated', "icij": False},

    # ──── ASIA & PACIFIC ────
    {"id": 'scmp', "country": 'Hong Kong', "region": 'Asia & Pacific', "name": 'South China Morning Post', "url": 'https://www.scmp.com', "status": 'state_adjacent', "icij": False, "frontpage": {"provider": "frontpages", "slug": "south-china-morning-post", "country_slug": "hong-kong"}},
    {"id": 'peoples_d', "country": 'China', "region": 'Asia & Pacific', "name": "People's Daily", "url": 'http://en.people.cn', "status": 'state_controlled', "icij": False, "frontpage": {"provider": "frontpages", "slug": "people-s-daily", "country_slug": "china"}},
    {"id": 'global_times', "country": 'China', "region": 'Asia & Pacific', "name": 'Global Times', "url": 'https://www.globaltimes.cn', "status": 'state_controlled', "icij": False, "frontpage": {"provider": "frontpages", "slug": "global-times", "country_slug": "china"}},
    {"id": 'liberty_times', "country": 'Taiwan', "region": 'Asia & Pacific', "name": 'Liberty Times', "url": 'https://www.ltn.com.tw', "status": 'independent', "icij": False, "frontpage": {"provider": "frontpages", "slug": "liberty-times", "country_slug": "taiwan"}},
    {"id": 'yomiuri', "country": 'Japan', "region": 'Asia & Pacific', "name": 'Yomiuri Shimbun', "url": 'https://www.yomiuri.co.jp', "status": 'independent', "icij": False, "frontpage": {"provider": "frontpages", "slug": "yomiuri-shinbun", "country_slug": "japan"}},
    {"id": 'asahi', "country": 'Japan', "region": 'Asia & Pacific', "name": 'Asahi Shimbun', "url": 'https://www.asahi.com', "status": 'independent', "icij": True},
    {"id": 'chosun', "country": 'South Korea', "region": 'Asia & Pacific', "name": 'Chosun Ilbo', "url": 'https://www.chosun.com', "status": 'independent', "icij": False},
    {"id": 'hankyoreh', "country": 'South Korea', "region": 'Asia & Pacific', "name": 'Hankyoreh', "url": 'https://www.hani.co.kr', "status": 'independent', "icij": False},
    {"id": 'the_hindu', "country": 'India', "region": 'Asia & Pacific', "name": 'The Hindu', "url": 'https://www.thehindu.com', "status": 'independent', "icij": True, "frontpage": {"provider": "frontpages", "slug": "the-hindu", "country_slug": "india"}},
    {"id": 'ind_express', "country": 'India', "region": 'Asia & Pacific', "name": 'Indian Express', "url": 'https://indianexpress.com', "status": 'independent', "icij": True},
    {"id": 'dawn', "country": 'Pakistan', "region": 'Asia & Pacific', "name": 'Dawn', "url": 'https://www.dawn.com', "status": 'independent', "icij": True, "frontpage": {"provider": "frontpages", "slug": "dawn", "country_slug": "pakistan"}},
    {"id": 'daily_star', "country": 'Bangladesh', "region": 'Asia & Pacific', "name": 'The Daily Star', "url": 'https://www.thedailystar.net', "status": 'independent', "icij": False},
    {"id": 'straits_t', "country": 'Singapore', "region": 'Asia & Pacific', "name": 'The Straits Times', "url": 'https://www.straitstimes.com', "status": 'state_adjacent', "icij": False, "frontpage": {"provider": "frontpages", "slug": "the-straits-times", "country_slug": "singapore"}},
    {"id": 'inquirer', "country": 'Philippines', "region": 'Asia & Pacific', "name": 'Philippine Daily Inquirer', "url": 'https://inquirer.net', "status": 'independent', "icij": True, "frontpage": {"provider": "frontpages", "slug": "philippine-daily-inquirer", "country_slug": "philippines"}},
    {"id": 'kompas', "country": 'Indonesia', "region": 'Asia & Pacific', "name": 'Kompas', "url": 'https://www.kompas.com', "status": 'independent', "icij": False, "frontpage": {"provider": "frontpages", "slug": "kompas", "country_slug": "indonesia"}},
    {"id": 'malaysiakini', "country": 'Malaysia', "region": 'Asia & Pacific', "name": 'Malaysiakini', "url": 'https://www.malaysiakini.com', "status": 'independent', "icij": True},
    {"id": 'irrawaddy', "country": 'Myanmar', "region": 'Asia & Pacific', "name": 'The Irrawaddy', "url": 'https://www.irrawaddy.com', "status": 'exile', "icij": False},
    {"id": 'smh', "country": 'Australia', "region": 'Asia & Pacific', "name": 'Sydney Morning Herald', "url": 'https://www.smh.com.au', "status": 'independent', "icij": True, "frontpage": {"provider": "frontpages", "slug": "the-sydney-morning-herald", "country_slug": "australia"}},
    {"id": 'the_aus', "country": 'Australia', "region": 'Asia & Pacific', "name": 'The Australian', "url": 'https://www.theaustralian.com.au', "status": 'independent', "icij": False, "frontpage": {"provider": "frontpages", "slug": "the-australian", "country_slug": "australia"}},
    {"id": 'nz_herald', "country": 'New Zealand', "region": 'Asia & Pacific', "name": 'NZ Herald', "url": 'https://www.nzherald.co.nz', "status": 'independent', "icij": False, "frontpage": {"provider": "frontpages", "slug": "the-new-zealand-herald", "country_slug": "new-zealand"}},
    {"id": 'tuoi_tre', "country": 'Vietnam', "region": 'Asia & Pacific', "name": 'Tuổi Trẻ', "url": 'https://tuoitre.vn', "status": 'state_affiliated', "icij": False},
    {"id": 'daily_mirror_lk', "country": 'Sri Lanka', "region": 'Asia & Pacific', "name": 'Daily Mirror (Sri Lanka)', "url": 'https://www.dailymirror.lk', "status": 'independent', "icij": False},
    {"id": 'kathmandu_post', "country": 'Nepal', "region": 'Asia & Pacific', "name": 'The Kathmandu Post', "url": 'https://kathmandupost.com', "status": 'independent', "icij": False},
    {"id": 'pp_post', "country": 'Cambodia', "region": 'Asia & Pacific', "name": 'Phnom Penh Post', "url": 'https://www.phnompenhpost.com', "status": 'state_adjacent', "icij": False},
    {"id": 'fiji_times', "country": 'Fiji', "region": 'Asia & Pacific', "name": 'The Fiji Times', "url": 'https://www.fijitimes.com.fj', "status": 'independent', "icij": False},
    {"id": 'caixin', "country": 'China', "region": 'Asia & Pacific', "name": 'Caixin', "url": 'https://www.caixin.com', "status": 'pressured', "icij": False},
    {"id": 'matichon', "country": 'Thailand', "region": 'Asia & Pacific', "name": 'Matichon', "url": 'https://www.matichon.co.th', "status": 'independent', "icij": False},
    {"id": 'thai_rath', "country": 'Thailand', "region": 'Asia & Pacific', "name": 'Thai Rath', "url": 'https://www.thairath.co.th', "status": 'independent', "icij": False},
    {"id": 'nikkei', "country": 'Japan', "region": 'Asia & Pacific', "name": 'Nikkei', "url": 'https://www.nikkei.com', "status": 'independent', "icij": False},
    {"id": 'postcourier_pg', "country": 'Papua New Guinea', "region": 'Asia & Pacific', "name": 'Post-Courier', "url": 'https://www.postcourier.com.pg', "status": 'independent', "icij": False},
    {"id": 'samoa_observer', "country": 'Samoa', "region": 'Asia & Pacific', "name": 'Samoa Observer', "url": 'https://www.samoaobserver.ws', "status": 'independent', "icij": False},
    {"id": 'dailypost_vu', "country": 'Vanuatu', "region": 'Asia & Pacific', "name": 'Daily Post (Vanuatu)', "url": 'https://www.dailypost.vu', "status": 'independent', "icij": False},
    {"id": 'solomon_star', "country": 'Solomon Islands', "region": 'Asia & Pacific', "name": 'Solomon Star', "url": 'https://www.solomonstarnews.com', "status": 'state_adjacent', "icij": False},

    # ──── ADDED FROM FRONTPAGE-PROVIDER BLIND-SPOT ANALYSIS (2026-07-17) ────
    # Not new countries -- all four are additional/alternative outlets in
    # countries already on this list, surfaced because they had verified
    # frontpage coverage and looked like a stronger or complementary "paper
    # of record" fit. Flagged for review, not silently substituted for the
    # existing pick in that country.
    {"id": 'thisday_ng', "country": 'Nigeria', "region": 'Africa & Middle East', "name": 'ThisDay', "url": 'https://www.thisdaylive.com', "status": 'independent', "icij": False, "frontpage": {"provider": "frontpages", "slug": "thisday", "country_slug": "nigeria"}},
    {"id": 'vanguard_ng', "country": 'Nigeria', "region": 'Africa & Middle East', "name": 'Vanguard', "url": 'https://www.vanguardngr.com', "status": 'independent', "icij": False, "frontpage": {"provider": "frontpages", "slug": "vanguard-nigeria", "country_slug": "nigeria"}},
    {"id": 'le_devoir', "country": 'Canada', "region": 'Americas', "name": 'Le Devoir', "url": 'https://www.ledevoir.com', "status": 'independent', "icij": False, "frontpage": {"provider": "frontpages", "slug": "le-devoir", "country_slug": "canada"}},
    {"id": 'business_day_za', "country": 'South Africa', "region": 'Africa & Middle East', "name": 'Business Day', "url": 'https://www.businesslive.co.za/bd/', "status": 'independent', "icij": False, "frontpage": {"provider": "frontpages", "slug": "business-day-za", "country_slug": "south-africa"}},
]

# Sources used as global baseline — excluded from newsletter output
# but used to calibrate what's already globally known
BASELINE_SOURCES = {"nyt", "wsj", "wapo", "guardian", "ft"}

# Status label copy for Substack output
STATUS_LABELS = {
    "state_controlled": "⚠️ State-controlled — editorial content reflects official government position",
    "state_affiliated": "⚠️ State-affiliated publication",
    "state_adjacent": "⚠️ State-adjacent — editorially professional, operates in proximity to government",
    "exile":          "⚠️ Exile publication — independent journalism published outside home country",
    "pressured":      "⚠️ Independent but operating under documented government pressure",
}

def get_sources(exclude_baseline=True):
    if exclude_baseline:
        return [s for s in SOURCES if s["id"] not in BASELINE_SOURCES]
    return SOURCES

def get_baseline_sources():
    return [s for s in SOURCES if s["id"] in BASELINE_SOURCES]
